trigger:
- master
- dev
- refs/tags/*

pr:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Prepare Python $(python.version)'
- script: pip install pipenv
  displayName: 'Install pipenv'
- script: python -m pipenv install --dev
  displayName: 'Install dependencies'
