name: curso-django

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.2
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -q pipenv
        pipenv sync -d
    - name: Lint with flake8
      run: |
        pipenv run flake8 .
    - name: Rodar Testes Automáticos
      run: |
        pipenv run pytest